[bumpver]
current_version = "2025.5.1.3"
version_pattern = "YYYY.MM.DD[.INC0]"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"platform/edge/manifest.json" = [
    '"version": "{version}"',
]
"platform/firefox/manifest.json" = [
    '"version": "{version}"',
]
"platform/chrome/manifest.json" = [
    '"version": "{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]

